export const ladiesServices = [
  'Amiga para un trio',
  'Atención Lésbica',
  'Atención Personas con Discapacidad',
  'Bailes eroticos',
  'Besos',
  'Despedidas',
  'Disfraces',
  'Dos chicas',
  'Ducha Érotica',
  'Eventos y Cenas',
  'Experiencia de novia (GFE)',
  'Fetichismo',
  'Juguetes',
  'Masaje a 4 manos',
  'Masaje de próstata',
  'Masaje Desnuda',
  'Masaje en Lenceria',
  'Masaje Érotico',
  'Masaje NO Profesional',
  'Masaje Profesional',
  'Masaje Tántrico',
  'Masturbación Rusa',
  'Oral Americana',
  'Oral Preservativo',
  'Oral sin Preservativo',
  'Parejas con Lésbico',
  'Parejas Hetero',
  'Porn Star Experiencia (PSE)',
  'Terminar en boca (CIM)',
  'Terminar en los senos (COB)',
].map((service, idx) => ({
  id: idx,
  name: service,
}));
