export { Root, type RootProps } from './root'
export { Media, type MediaProps } from './media'
export { Content, type ContentProps } from './content'
export { Title, type TitleProps } from './title'
export { Description, type DescriptionProps } from './description'
export { Footer, type FooterProps } from './footer'
