import Icons from './Icons'

export const {
  Arrow90degRightIcon,
  ArrowRightIcon,
  BoxArrowRightIcon,
  CaretLeftFillIcon,
  CaretRightFillIcon,
  CheckIcon,
  CheckSquareIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CoinIcon,
  DoorOpenIcon,
  EnvelopeIcon,
  FacebookIcon,
  FilterCircleFillIcon,
  GemIcon,
  GeoAltFillIcon,
  Globe2Icon,
  HeartFillIcon,
  HouseFillIcon,
  InstagramIcon,
  ListIcon,
  LogoIcon,
  MoonIcon,
  PatchCheckFillIcon,
  PersonCircleIcon,
  SearchIcon,
  ShareFillIcon,
  SortDownIcon,
  SquareIcon,
  SuitHeartFillIcon,
  SunIcon,
  TiktokIcon,
  TwitterIcon,
  WhatsappIcon,
  XCircleFillIcon,
} = Icons
