import Icons from './Icons'

export const {
  Arrow90degRightIcon,
  BoxArrowRightIcon,
  CaretLeftFillIcon,
  CaretRightFillIcon,
  CheckIcon,
  CheckSquareIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CoinIcon,
  DoorOpenIcon,
  EnvelopeIcon,
  FacebookIcon,
  FilterCircleFillIcon,
  GeoAltFillIcon,
  Globe2Icon,
  HouseFillIcon,
  InstagramIcon,
  LogoIcon,
  MoonIcon,
  PatchCheckFillIcon,
  PersonCircleIcon,
  SearchIcon,
  ShareFillIcon,
  SquareIcon,
  SuitHeartFillIcon,
  SunIcon,
  TiktokIcon,
  TwitterIcon,
  WhatsappIcon,
  XCircleFillIcon,
} = Icons
